<?php
/**
 * @file
 * testimonials.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function testimonials_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_options_testimonials';
  $strongarm->value = array(
    0 => 'menu-about-menu',
    1 => 'main-menu',
  );
  $export['menu_options_testimonials'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_parent_testimonials';
  $strongarm->value = 'main-menu:0';
  $export['menu_parent_testimonials'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_options_testimonials';
  $strongarm->value = array(
    0 => 'status',
  );
  $export['node_options_testimonials'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_preview_testimonials';
  $strongarm->value = '1';
  $export['node_preview_testimonials'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_submitted_testimonials';
  $strongarm->value = 0;
  $export['node_submitted_testimonials'] = $strongarm;

  return $export;
}
